export const INCREMENT_PAGE_NUM = 'INCREMENT_PAGE_NUM';
export const DECREMENT_PAGE_NUM = 'DECREMENT_PAGE_NUM';
export const RESET_PAGE_NUM = 'RESET_PAGE_NUM';

export const UPDATE_ANSWERS = 'UPDATE_ANSWERS';
export const RESET_DATA = 'RESET_DATA';
